### ISSUE TITLE
Where should it work?

### ISSUE THREAD

**Issue by nicolagalvanetto** [addshore/chrome-github-release-downloads#6]
Nice initiative addshore, 
But in my page https://github.com/nicolagalvanetto/Fodis/releases does not show any info...
The small icon on the top right remains grey.

Could you please be more specific on the behavior of the extension?

**Comment by aonez** [comment]
You need to add some downloads. The source code does not get download counts.

**Comment by addshore** [comment]
Yup, @aonez is correct.
The source code zips don't have any download counts provided by the github API.
