### ISSUE TITLE
GitHub releases structure changed again

### ISSUE THREAD

**Issue by aonez** [addshore/chrome-github-release-downloads#8]
Just in case you need that one again, in my case just this change fixed the issue:

https://github.com/addshore/chrome-github-release-downloads/blob/d56127b4c4fcc05034f8e545237fc69d384ae548/app/scripts.babel/contentscript.js#L29

For:
```js
el.parentNode.insertBefore(dwnCount, size);
```

Complete commit here https://github.com/aonez/GitHubCounter/commit/9d47ce8ea3019d961944e601ca21e24c65011ad6. They now use flex boxes, so adding `flex-grow: 2` and `text-align: right` to your download element style might be needed.

Salut!

**Comment by addshore** [comment]
Thanks!
Patches and released as 1.3.0, going to update it in the "store" now.
I also added your CSS this time too :)

**Comment by aonez** [comment]
Nice! It's less intrusive with the downloads icon instead of label 😉
